name: my_wird
description: "تطبيق لتذكير المستخدم بقراءة القرآن يوميًا باستخدام Alquran Cloud API."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  lottie: ^3.3.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Amiri-Regular.ttf
    - assets/lottie/mamafatma.json
    - assets/icon/icon_app.png # Required for launcher icon

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_app.png"
